const ADD_CONTROL = "ADD_CONTROL"
const DELETE_CONTROL = "DELETE_CONTROL"
const UPDATEA_CONTROL = "UPDATEA_CONTROL"
const TOGGLE_CONTROL = "TOGGLE_CONTROL"
export {
    ADD_CONTROL,
    DELETE_CONTROL,
    UPDATEA_CONTROL,
    TOGGLE_CONTROL
}