const ADD_CONTROL = "ADD_CONTROL"
const DELETE_CONTROL = "DELETE_CONTROL"
const TOGGLE_CONTROL = "TOGGLE_CONTROL"
const UPDATEA_CONTROL = "UPDATEA_CONTROL"
const SET_CURRENT_CONTROL_ID = "SET_CURRENT_CONTROL_ID"
const CLEAR_CURRENT_CONTROL = "CLEAR_CURRENT_CONTROL"

export {
    ADD_CONTROL,
    DELETE_CONTROL,
    TOGGLE_CONTROL,
    UPDATEA_CONTROL,
    SET_CURRENT_CONTROL_ID,
    CLEAR_CURRENT_CONTROL
}
