const allControls = [
    {
        label:"基础控件",
        icon:"bug",
        children:[
            {
                label:"文本框",
                icon:"bug",
                id:"CONTROL_TEXT"
            },{
                label:"下拉框",
                icon:"bug",
                id:"CONTROL_SELECT"
            },{
                label:"按钮",
                icon:"bug",
                id:"CONTROL_BUTTON"
            },{
                label:"单选框",
                icon:"bug",
                id:"CONTROL_RADIO"
            },{
                label:"多选框",
                icon:"bug",
                id:"CONTROL_CHECKBOX"
            },{
                label:"IP",
                icon:"bug",
                id:"CONTROL_IP"
            },{
                label:"表格",
                icon:"bug",
                id:"CONTROL_TABLE"
            },{
                label:"树",
                icon:"bug",
                id:"CONTROL_TREE"
            },{
                label:"动态表格",
                icon:"bug",
                id:"CONTROL_DYNAMIC_TABLE"
            },{
                label:"时间",
                icon:"bug",
                id:"CONTROL_TIME"
            },{
                label:"密码",
                icon:"bug",
                id:"CONTROL_PASSWORD"
            },{
                label:"数字",
                icon:"bug",
                id:"CONTROL_NUMBER"
            },{
                label:"静态图片",
                icon:"bug",
                id:"CONTROL_IMAGE"
            },{
                label:"图片上传",
                icon:"bug",
                id:"CONTROL_UPLOAD"
            },{
                label:"超链接",
                icon:"bug",
                id:"CONTROL_LINK"
            }
        ]
    },{
        label:"布局控件",
        icon:"bug",
        children:[
            {
                label:"表格布局",
                icon:"bug",
                id:"LAYOUT_TABLE"
            },,{
                label:"栅格布局",
                icon:"bug",
                id:"LAYOUT_GRID"
            },{
                label:"标签页布局",
                icon:"bug",
                id:"CONTROL_TAB"
            },{
                label:"块布局",
                icon:"bug",
                id:"CONTROL_BLOCK"
            }
        ]
    },{
        label:"统计控件",
        icon:"bug",
        children:[
            {
                label:"统计表格",
                icon:"bug",
                id:"STATISTICS_TABLE"
            },{
                label:"饼图",
                icon:"bug",
                id:"STATISTICS_PIE_CHART"
            },{
                label:"曲线图",
                icon:"bug",
                id:"STATISTICS_CURVE"
            }
        ]
    },{
        label:"手机控件",
        icon:"bug",
        children:[]
    },{
        label:"流程控件",
        icon:"bug",
        children:[]
    },
]

export default allControls